// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhaGHnUxvsn4e_W6AI5Uvx42Id73KBJ9E',
    appId: '1:1058070847340:web:7b4ead00acac95acff5d49',
    messagingSenderId: '1058070847340',
    projectId: 'welloapp-ee88a',
    authDomain: 'welloapp-ee88a.firebaseapp.com',
    storageBucket: 'welloapp-ee88a.firebasestorage.app',
    measurementId: 'G-Z6ED4430G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUqozLtWRFzcohZt3lUW6nEQ8D0KyFM-I',
    appId: '1:1058070847340:android:9dd3d34e96ded757ff5d49',
    messagingSenderId: '1058070847340',
    projectId: 'welloapp-ee88a',
    storageBucket: 'welloapp-ee88a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc5c6FQ83y2TbUq8t0Dy8U_atYb6U21Ws',
    appId: '1:1058070847340:ios:8a4478f53cdaa4afff5d49',
    messagingSenderId: '1058070847340',
    projectId: 'welloapp-ee88a',
    storageBucket: 'welloapp-ee88a.firebasestorage.app',
    iosBundleId: 'com.example.welloFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc5c6FQ83y2TbUq8t0Dy8U_atYb6U21Ws',
    appId: '1:1058070847340:ios:8a4478f53cdaa4afff5d49',
    messagingSenderId: '1058070847340',
    projectId: 'welloapp-ee88a',
    storageBucket: 'welloapp-ee88a.firebasestorage.app',
    iosBundleId: 'com.example.welloFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhaGHnUxvsn4e_W6AI5Uvx42Id73KBJ9E',
    appId: '1:1058070847340:web:d26074ca96533f4eff5d49',
    messagingSenderId: '1058070847340',
    projectId: 'welloapp-ee88a',
    authDomain: 'welloapp-ee88a.firebaseapp.com',
    storageBucket: 'welloapp-ee88a.firebasestorage.app',
    measurementId: 'G-1CNZ48N2NW',
  );
}
